CREATE TABLE IF NOT EXISTS "fait_vente" (
	"order_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"order_info" INTEGER NOT NULL,
	"customer_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"return_id" INTEGER,
	"qty" INTEGER NOT NULL,
	"price" MONEY NOT NULL,
	PRIMARY KEY("order_id")
);




CREATE TABLE IF NOT EXISTS "dim_return" (
	"return_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"return_ts" DATE NOT NULL,
	"reason" VARCHAR(255) NOT NULL,
	"amount" MONEY NOT NULL,
	PRIMARY KEY("return_id")
);




CREATE TABLE IF NOT EXISTS "dim_product" (
	"product_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"category" VARCHAR(255) NOT NULL,
	"subcategory" VARCHAR(255) NOT NULL,
	"brand" VARCHAR(255) NOT NULL,
	"list_price" MONEY NOT NULL,
	PRIMARY KEY("product_id")
);




CREATE TABLE IF NOT EXISTS "dim_order_info" (
	"order_info_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"customer_id" INTEGER NOT NULL,
	"order_ts" DATE NOT NULL,
	"status" VARCHAR(255) NOT NULL,
	"channel" VARCHAR(255) NOT NULL,
	"currency" VARCHAR(255) NOT NULL,
	PRIMARY KEY("order_info_id")
);




CREATE TABLE IF NOT EXISTS "dim_customer" (
	"customer_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"gender" CHAR(1) NOT NULL,
	"birthdate" DATE NOT NULL,
	"city" VARCHAR(255) NOT NULL,
	"country" VARCHAR(255) NOT NULL,
	"registration_date" DATE NOT NULL,
	PRIMARY KEY("customer_id")
);


ALTER TABLE "dim_return"
ADD FOREIGN KEY("return_id") REFERENCES "fait_vente"("return_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_product"
ADD FOREIGN KEY("product_id") REFERENCES "fait_vente"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_order_info"
ADD FOREIGN KEY("order_info_id") REFERENCES "fait_vente"("order_info")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dim_customer"
ADD FOREIGN KEY("customer_id") REFERENCES "fait_vente"("customer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;