DROP TABLE IF EXISTS "stg_products";
DROP TABLE IF EXISTS "stg_customers";
DROP TABLE IF EXISTS "stg_order_items";
DROP TABLE IF EXISTS "stg_orders";
DROP TABLE IF EXISTS "stg_returns";
DROP TABLE IF EXISTS "fact_ventes";
DROP TABLE IF EXISTS "dim_returns";
DROP TABLE IF EXISTS "dim_products";
DROP TABLE IF EXISTS "dim_orders";
DROP TABLE IF EXISTS "dim_customers";

-- STAGING TABLES

CREATE TABLE IF NOT EXISTS "stg_products" (
	"product_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"category" TEXT,
	"subcategory" TEXT,
	"brand" TEXT,
	"list_price" DOUBLE PRECISION,
	PRIMARY KEY("product_id")
);




CREATE TABLE IF NOT EXISTS "stg_customers" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"gender" TEXT,
	"birthdate" TEXT, --DATE,
	"city" TEXT,
	"country" TEXT,
	"registration_date" TEXT, --DATE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "stg_order_items" (
	"order_id" INTEGER,
	"product_id" INTEGER,
	"qty" INTEGER,
	"unit_price" DOUBLE PRECISION,
	"discount" DOUBLE PRECISION
);




CREATE TABLE IF NOT EXISTS "stg_orders" (
	"order_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"customer_id" INTEGER,
	"order_ts" TEXT, --DATE,
	"status" TEXT,
	"channel" TEXT,
	"currency" TEXT,
	PRIMARY KEY("order_id")
);




CREATE TABLE IF NOT EXISTS "stg_returns" (
	"return_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"order_id" INTEGER,
	"product_id" INTEGER,
	"return_ts" TEXT, --DATE,
	"reason" TEXT,
	"amount" DOUBLE PRECISION,
	PRIMARY KEY("return_id")
);




-- FACT & DIM TABLES

CREATE TABLE IF NOT EXISTS "fact_ventes" (
	"order_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"order_info" INTEGER NOT NULL,
	"customer_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"return_id" INTEGER,
	"qty" INTEGER NOT NULL,
	"price" DOUBLE PRECISION NOT NULL,
	PRIMARY KEY("order_id")
);




CREATE TABLE IF NOT EXISTS "dim_returns" (
	"return_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"return_ts" TEXT, --DATE NOT NULL,
	"reason" TEXT NOT NULL,
	"amount" DOUBLE PRECISION NOT NULL,
	PRIMARY KEY("return_id")
);




CREATE TABLE IF NOT EXISTS "dim_products" (
	"product_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT NOT NULL,
	"category" TEXT NOT NULL,
	"subcategory" TEXT NOT NULL,
	"brand" TEXT NOT NULL,
	"list_price" DOUBLE PRECISION NOT NULL,
	PRIMARY KEY("product_id")
);




CREATE TABLE IF NOT EXISTS "dim_orders" (
	"order_info_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"order_ts" TEXT, --DATE NOT NULL,
	"status" TEXT NOT NULL,
	"channel" TEXT NOT NULL,
	"currency" TEXT NOT NULL,
	PRIMARY KEY("order_info_id")
);




CREATE TABLE IF NOT EXISTS "dim_customers" (
	"customer_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"gender" CHAR(1) NOT NULL,
	"birthdate" TEXT, --DATE NOT NULL,
	"city" TEXT NOT NULL,
	"country" TEXT NOT NULL,
	"registration_date" TEXT, --DATE NOT NULL,
	PRIMARY KEY("customer_id")
);

ALTER TABLE "fact_ventes"
ADD FOREIGN KEY("return_id") REFERENCES "dim_returns"("return_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_ventes"
ADD FOREIGN KEY("product_id") REFERENCES "dim_products"("product_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_ventes"
ADD FOREIGN KEY("order_info") REFERENCES "dim_orders"("order_info_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "fact_ventes"
ADD FOREIGN KEY("customer_id") REFERENCES "dim_customers"("customer_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;